### ISSUE TITLE
Is it working with Rails 5?

### ISSUE THREAD

**Issue by francescor** [fusioncharts/rails-wrapper#5]
I am not able to run it in Rails 5

**Comment by swaroopsm** [comment]
@francescor Could you elaborate this providing as to what are the errors / warnings that you are receiving while you integrated this?

**Comment by nagarjunac** [comment]
dashboard:686 Uncaught ReferenceError: FusionCharts is not defined

**Comment by rahul-kr2000** [comment]
Please write to support@fusioncharts.com, we'll help you out.
